version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: vt-data-pipeline-redis
    ports:
      - "6379:6379"  # Redis
      - "8001:8001"  # RedisInsight
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    networks:
      - vt-network

volumes:
  redis_data:

networks:
  vt-network:
    driver: bridge