version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: vt-data-pipeline-redis
    ports:
      - "6379:6379" # Redis
      - "8001:8001" # RedisInsight
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    networks:
      - vt-network

  postgres:
    image: postgres:15
    container_name: vt-data-pipeline-postgres
    environment:
      POSTGRES_USER: vt_data_pipeline
      POSTGRES_PASSWORD: vt_data_pipeline_password
      POSTGRES_DB: vt_data_pipeline
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vt-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: vt-data-pipeline-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - vt-network

volumes:
  redis_data:
  postgres_data:


networks:
  vt-network:
    driver: bridge
